### ISSUE TITLE
Elements that needs to be updated.

### ISSUE THREAD

**Issue by TUSK3N** [pazuzu156/undead-discord#1]
The new Discord update broke some of the theme and I'll try and screenshot everything I notice.

The Voice connected box isn't the same color as the rest it's the default one.
![image](https://user-images.githubusercontent.com/17619692/39551327-e352dbe2-4e64-11e8-938d-1024fbcbc9fc.png)

Hovering over a user in the member list gives the default Discord color.
![image](https://user-images.githubusercontent.com/17619692/39551384-18943df0-4e65-11e8-8bff-254a2ccaa519.png)

All of the users in the member list has gone back to the default circle avatars instead of the square shaped avatars.
![image](https://user-images.githubusercontent.com/17619692/39551423-3f45c1f8-4e65-11e8-993b-92b144096d17.png)

The embeds have gone back to the default color in chat.
![image](https://user-images.githubusercontent.com/17619692/39551487-74099a4a-4e65-11e8-9a5a-5468103e3191.png)

The profile has gone back to the default again with circles not squares.
![image](https://user-images.githubusercontent.com/17619692/39551532-a2e1a9a2-4e65-11e8-8c1e-1af966608aef.png)

Server settings menu has gone back to the default Discord color.
![image](https://user-images.githubusercontent.com/17619692/39551617-f9d073d8-4e65-11e8-809c-dff5562dfa80.png)

Update: Also the emote menu is back to white.
![image](https://user-images.githubusercontent.com/17619692/39551801-ca6db820-4e66-11e8-8839-57f1ca82c844.png)

This also when you click on a user.
![image](https://user-images.githubusercontent.com/17619692/39551903-3cda162e-4e67-11e8-8646-edc8852ad9a1.png)

When you right click a message it shows the default color.
![image](https://user-images.githubusercontent.com/17619692/39552039-cdd18a90-4e67-11e8-90f7-b63bcd1ba331.png)

I'll see if I can find anything else in the meantime thanks for updating this theme it's so clean.

**Comment by pazuzu156** [comment]
Yup, I got it. I made an update to it yesterday as there was plenty more broken. I forgot a few things, which you seem to have found. I've also decided to sorta "redo" the code. It'll look and act exactly the same, just the building aspect will be different. I'll leave this issue open until I've fixed them. Thanks for the heads-up!

**Comment by TUSK3N** [comment]
I know this isn't about the bugs but before it was easy for me to use this Theme because I could do this Custom CSS

@import url("https://rawgit.com/pazuzu156/undead-discord/master/undead-discord.css");

and it would update itself everytime I restarted Discord and now it's not the same with your method :(

**Comment by pazuzu156** [comment]
That's due to how I've reconstructed the development environment for the theme. Since it's using Sass now, it needs something to build it, and that's what I've done.

I've gone ahead and opened up a `build` branch with just the compiled CSS, so you can continue using the `@import` directive. Here's the rawgit URL: [https://rawgit.com/pazuzu156/undead-discord/build/dist/undead-discord.min.css](https://rawgit.com/pazuzu156/undead-discord/build/dist/undead-discord.min.css)

I've tested this, and it's working. So it would work for you too.

**Comment by TUSK3N** [comment]
Thank you dude!

also

Avatars are currently circles in voice channels I think it used to be squares there also.
![image](https://user-images.githubusercontent.com/17619692/39675582-61ffe3a4-515d-11e8-89dd-7c56184c89b9.png)

Hovering over something shows the default blue boxes everywhere.
![image](https://user-images.githubusercontent.com/17619692/39675589-85826d74-515d-11e8-8217-a5ef6a470fd8.png)

Also when someone is playing something that has the playing status the profile changes to the standard blue one

![image](https://user-images.githubusercontent.com/17619692/39675628-21652826-515e-11e8-9131-96bb9e641404.png)

![image](https://user-images.githubusercontent.com/17619692/39675633-2e7b6b2e-515e-11e8-8a24-2d8dbe45ee57.png)

The upper part of the profile.

**Comment by pazuzu156** [comment]
The profile popup has always done that. I can change it to something else if you think it would look better. 

As for blue on guild highlights, that should be fixed. If I failed to make an update to the build branch I'll fix that. 

Are you running from the desktop app or a browser?

**Comment by TUSK3N** [comment]
I'm using the desktop app with BetterDiscord and I'm not sure if the profile showed up as blue before I'm pretty sure with this theme it way always dark on the profile except for the spotify playing status that has stayed green.

I updated it right now and it doesn't seem to be fixed so I guess it didn't work.

**Comment by pazuzu156** [comment]
I'm building this using BeautifulDiscord, and haven't used BetterDiscord with the theme. I'll give it a go and see if there are any differences, but I recommend using BeautifulDiscord.

**Comment by pazuzu156** [comment]
Closing this issue. Please re-open on [GitLab](https://gitlab.com/pazuzu156/undead-discord/issues) if you still need it
